### PR TITLE
add xml import/dump feature to uabea

### PR DESCRIPTION
**Pull request by HxBreak**
This commit is only for add xml dump import and export

### CODE REVIEW

**Comment by mskgroup** [comment]
It seems that dll cannot be automatically loaded when xml is exported, so the exported monobehaviour is not completed

**Comment by HxBreak** [comment]
This is just a pure format support.

`am.GetMonoBaseFieldCached(assetFileInstance, assetFileInfoEx, dll_path);`
https://github.com/HxBreak/UABEA/blob/1eb04a78ca4cb1301f5ff57ba974542298c13c30/UABEAvalonia/InfoWindow.axaml.cs

This will help you dump monobehaviour as txt/xml

**Comment by HxBreak** [comment]
@mskgroup

**Comment by mskgroup** [comment]
谢了老哥 thx

**Pull request closed without merging**
